use std::path::PathBuf;
use std::process::ExitCode;
use std::str::FromStr;

use clap::{Parser, Subcommand};
use tracing_subscriber::EnvFilter;

use mallard::pr_review::{self, PrReviewRequest};
use mallard::{
    BuildRequest, Direction, EdgeKind, FindingFilter, IndexReader, QueryRequest, SymbolId, build,
    symbol_diff,
};

#[derive(Parser, Debug)]
#[command(name = "mallard", version, about = "AI-native repository index")]
struct Cli {
    #[command(subcommand)]
    command: Cmd,
}

#[derive(Subcommand, Debug)]
enum Cmd {
    /// Build an index of a repository at a specific commit SHA.
    Index(IndexArgs),
    /// Query a built index.
    Query(QueryArgs),
    /// Run deterministic-only PR review across two indexes (base / head).
    /// Emits comments tagged by confidence tier — no LLM call, ever.
    /// Mallard's permanent product shape is deterministic-only per ADR-0013.
    PrReview(PrReviewArgs),
    /// Emit per-file `DiffHunks` JSON for consumption by `pr-review`.
    /// Wraps `git diff --unified=0 <base> <head>` and parses the unified
    /// diff hunks (`@@ -A,B +C,D @@` headers) into the JSON shape.
    DiffHunks(DiffHunksArgs),
    /// Lightweight cross-index symbol diff. Returns added / removed /
    /// modified symbols by `(qualified_name, path)` matching. Cheaper
    /// than `pr-review` — no rule findings, no comment budget. Use when
    /// an agent just wants "what symbols changed between these two SHAs?"
    SymbolDiff(SymbolDiffArgs),
}

#[derive(Parser, Debug)]
struct PrReviewArgs {
    #[arg(long = "base-db")]
    base_db: PathBuf,
    #[arg(long = "head-db")]
    head_db: PathBuf,
    /// Comma-separated changed file paths (relative to repo root).
    #[arg(long = "files", value_delimiter = ',')]
    files: Vec<String>,
    /// Optional path to a `DiffHunks` JSON file. Shape:
    /// `{ "files": { "<path>": [{"start": N, "end": M}, ...] } }`.
    /// When provided, enables Finding-7 `modified-body-touched` detection
    /// for stable-ID symbols whose anchors overlap the diff hunks.
    /// Generated by the GitHub Action via `mallard diff-hunks`.
    #[arg(long = "diff-hunks")]
    diff_hunks: Option<PathBuf>,
    /// Suppress `modified-body-touched` comments on test files whose
    /// diff overlap covers ≤ 2 lines. Test fixtures routinely flip
    /// literal expectations; the touched signal is structurally
    /// correct but adds no review value. Off by default.
    #[arg(long = "ignore-test-trivia", default_value_t = false)]
    ignore_test_trivia: bool,
    #[arg(long = "max-comments", default_value_t = 10)]
    max_comments: usize,
    /// Output format: `json` (default) or `markdown`.
    #[arg(long, default_value = "json")]
    format: String,
}

/// Args for the `diff-hunks` helper subcommand. Wraps `git diff
/// --unified=0` and emits the JSON format `pr-review --diff-hunks`
/// consumes, so the GitHub Action stays dependency-free (no awk / jq /
/// python in the pipeline).
#[derive(Parser, Debug)]
struct DiffHunksArgs {
    #[arg(long = "base-sha")]
    base_sha: String,
    #[arg(long = "head-sha")]
    head_sha: String,
    /// Repo path. Defaults to the current directory.
    #[arg(long, default_value = ".")]
    repo: PathBuf,
}

#[derive(Parser, Debug)]
struct SymbolDiffArgs {
    #[arg(long = "base-db")]
    base_db: PathBuf,
    #[arg(long = "head-db")]
    head_db: PathBuf,
}

#[derive(Parser, Debug)]
struct IndexArgs {
    path: PathBuf,
    #[arg(long)]
    sha: String,
    /// User-supplied rules YAML. Takes precedence over `--rules-bundled`.
    #[arg(long)]
    rules: Option<PathBuf>,
    /// Load the curated default rule pack baked into the binary. Set by
    /// the `mallard-review` GitHub Action when no per-repo rules path is
    /// provided. Ignored when `--rules` is set.
    #[arg(long = "rules-bundled", default_value_t = false)]
    rules_bundled: bool,
    #[arg(long)]
    out: Option<PathBuf>,
    #[arg(long, default_value_t = 1024 * 1024)]
    max_file_bytes: u64,
    #[arg(long = "lang")]
    languages: Vec<String>,
    #[arg(long, default_value_t = 10)]
    slowest_files_n: usize,
}

#[derive(Parser, Debug)]
struct QueryArgs {
    #[command(subcommand)]
    sub: QueryCmd,
}

#[derive(Subcommand, Debug)]
enum QueryCmd {
    /// Point lookup by symbol ID.
    Symbol {
        id: String,
        #[arg(long)]
        index: PathBuf,
    },
    /// Direct neighbors of a symbol.
    Neighbors {
        id: String,
        #[arg(long)]
        index: PathBuf,
        /// Comma-separated edge kinds. Empty = all kinds.
        #[arg(long, default_value = "")]
        kind: String,
        #[arg(long, default_value = "both")]
        direction: String,
    },
    /// Bounded neighborhood expansion.
    Expand {
        id: String,
        #[arg(long)]
        index: PathBuf,
        #[arg(long)]
        depth: u32,
        #[arg(long, default_value = "")]
        kind: String,
        #[arg(long, default_value = "both")]
        direction: String,
    },
    /// Structural rule findings.
    Findings {
        #[arg(long)]
        index: PathBuf,
        #[arg(long)]
        rule: Option<String>,
        #[arg(long = "path-prefix")]
        path_prefix: Option<String>,
        #[arg(long = "symbol-id")]
        symbol_id: Option<String>,
    },
    /// Symbols defined in a file.
    SymbolsInFile {
        path: String,
        #[arg(long)]
        index: PathBuf,
    },
    /// All symbols in a file with their outbound + inbound edges.
    EdgesByFile {
        path: String,
        #[arg(long)]
        index: PathBuf,
        #[arg(long, default_value = "")]
        kind: String,
        #[arg(long, default_value = "both")]
        direction: String,
    },
    /// All call sites pointing at any of the given unresolved names.
    /// Use for orphan-caller scans (e.g. after removing a public function).
    UnresolvedCallers {
        #[arg(long)]
        index: PathBuf,
        /// Comma-separated unresolved names to match.
        #[arg(long, value_delimiter = ',')]
        name: Vec<String>,
        #[arg(long, default_value = "")]
        kind: String,
    },
    /// Symbols whose file imports the given file path.
    ImportersOf {
        path: String,
        #[arg(long)]
        index: PathBuf,
    },
    /// Files whose path starts with the given prefix.
    Files {
        #[arg(long)]
        index: PathBuf,
        #[arg(long, default_value = "")]
        prefix: String,
    },
    /// Index metadata.
    Metadata {
        #[arg(long)]
        index: PathBuf,
    },
    /// Find symbols by qualified name. Exact match ranks first, then
    /// suffix matches (`*.qname`). Use when an agent has a short name
    /// like `foo` and needs the full symbol record.
    Find {
        #[arg(long)]
        index: PathBuf,
        #[arg(long)]
        qname: String,
    },
    /// Composite blast-radius lookup by qualified name. Returns the
    /// symbol, its callers, callees, test seams, and any sibling qname
    /// matches in one shot. Use BEFORE renaming, removing, or modifying
    /// a public symbol to scope refactor impact.
    BlastRadius {
        #[arg(long)]
        index: PathBuf,
        #[arg(long)]
        qname: String,
    },
    /// Test seams targeting a symbol — callers from files classified as
    /// test files. Use to find which tests to run after modifying a symbol.
    TestSeams {
        #[arg(long)]
        index: PathBuf,
        #[arg(long)]
        qname: String,
    },
}

fn main() -> ExitCode {
    let filter = EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("warn"));
    tracing_subscriber::fmt()
        .with_env_filter(filter)
        .with_target(false)
        .with_writer(std::io::stderr)
        .init();

    let cli = Cli::parse();
    let result = match cli.command {
        Cmd::Index(args) => run_index(args),
        Cmd::Query(args) => run_query(args),
        Cmd::PrReview(args) => run_pr_review(args),
        Cmd::DiffHunks(args) => run_diff_hunks(args),
        Cmd::SymbolDiff(args) => run_symbol_diff(args),
    };
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("error: {e}");
            ExitCode::FAILURE
        }
    }
}

fn run_index(args: IndexArgs) -> anyhow::Result<()> {
    let sha_prefix: String = args.sha.chars().take(12).collect();
    let out = args
        .out
        .unwrap_or_else(|| PathBuf::from(".mallard").join(format!("index-{sha_prefix}.duckdb")));

    let req = BuildRequest {
        root: args.path,
        sha: args.sha,
        rules_path: args.rules,
        rules_bundled: args.rules_bundled,
        out_path: out,
        max_file_bytes: args.max_file_bytes,
        language_allow_list: args.languages,
        slowest_files_n: args.slowest_files_n,
    };

    let summary = build(req)?;
    println!("{}", serde_json::to_string_pretty(&summary)?);
    Ok(())
}

fn parse_kinds(s: &str) -> anyhow::Result<Vec<EdgeKind>> {
    s.split(',')
        .map(str::trim)
        .filter(|t| !t.is_empty())
        .map(|t| EdgeKind::from_str(t).map_err(|_| anyhow::anyhow!("unknown edge kind: {t}")))
        .collect()
}

fn print<T: serde::Serialize>(value: &T) -> anyhow::Result<()> {
    println!("{}", serde_json::to_string_pretty(value)?);
    Ok(())
}

/// JSON contract version for the agent-facing surface — `find`, `blast-radius`,
/// `test-seams`, `symbol-diff`. Bumped via SemVer on any breaking shape change.
/// Older query primitives keep their unversioned shape for back-compat with
/// existing tooling (the `mallard-review` Action and ADR-0007 composition
/// patterns); see `docs/cli-json-contract.md`.
const CLI_SCHEMA_VERSION: &str = "1.0";

fn print_versioned<T: serde::Serialize>(value: &T) -> anyhow::Result<()> {
    let mut v = serde_json::to_value(value)?;
    if let serde_json::Value::Object(ref mut m) = v {
        m.insert(
            "schema_version".to_string(),
            serde_json::Value::String(CLI_SCHEMA_VERSION.to_string()),
        );
    }
    println!("{}", serde_json::to_string_pretty(&v)?);
    Ok(())
}

fn run_pr_review(args: PrReviewArgs) -> anyhow::Result<()> {
    let diff_hunks = match args.diff_hunks {
        Some(path) => {
            let bytes = std::fs::read(&path)
                .map_err(|e| anyhow::anyhow!("reading {}: {e}", path.display()))?;
            Some(serde_json::from_slice::<pr_review::DiffHunks>(&bytes)?)
        }
        None => None,
    };
    let result = pr_review::run(PrReviewRequest {
        base_db: args.base_db,
        head_db: args.head_db,
        changed_files: args.files,
        max_comments: args.max_comments,
        diff_hunks,
        ignore_test_trivia: args.ignore_test_trivia,
    })?;
    match args.format.as_str() {
        "markdown" => {
            println!("{}", pr_review::render_markdown(&result));
        }
        _ => {
            println!("{}", serde_json::to_string_pretty(&result)?);
        }
    }
    Ok(())
}

fn run_symbol_diff(args: SymbolDiffArgs) -> anyhow::Result<()> {
    let base = IndexReader::open(&args.base_db)?;
    let head = IndexReader::open(&args.head_db)?;
    let diff = symbol_diff(&base, &head)?;
    print_versioned(&diff)
}

fn run_diff_hunks(args: DiffHunksArgs) -> anyhow::Result<()> {
    let output = std::process::Command::new("git")
        .arg("-C")
        .arg(&args.repo)
        .arg("diff")
        .arg("--unified=0")
        .arg(&args.base_sha)
        .arg(&args.head_sha)
        .output()
        .map_err(|e| anyhow::anyhow!("running git diff: {e}"))?;
    if !output.status.success() {
        return Err(anyhow::anyhow!(
            "git diff failed: {}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    let diff = String::from_utf8_lossy(&output.stdout);
    let hunks = pr_review::parse_unified_diff_hunks(&diff);
    println!("{}", serde_json::to_string_pretty(&hunks)?);
    Ok(())
}

fn run_query(args: QueryArgs) -> anyhow::Result<()> {
    let (index, request) = to_request(args.sub)?;
    let result = IndexReader::open(&index)?.run(&request)?;
    if is_versioned_request(&request) {
        print_versioned(&result)
    } else {
        print(&result)
    }
}

/// Agent-facing primitives emit `schema_version`; legacy primitives stay
/// shape-stable for ADR-0007 compositions and downstream `jq` pipelines.
fn is_versioned_request(req: &QueryRequest) -> bool {
    matches!(
        req,
        QueryRequest::FindByQname { .. }
            | QueryRequest::BlastRadius { .. }
            | QueryRequest::TestSeams { .. }
    )
}

fn to_request(cmd: QueryCmd) -> anyhow::Result<(std::path::PathBuf, QueryRequest)> {
    Ok(match cmd {
        QueryCmd::Symbol { id, index } => (index, QueryRequest::LookupSymbol { id: SymbolId(id) }),
        QueryCmd::Neighbors {
            id,
            index,
            kind,
            direction,
        } => (
            index,
            QueryRequest::Neighbors {
                id: SymbolId(id),
                kinds: parse_kinds(&kind)?,
                direction: Direction::from_str(&direction)?,
            },
        ),
        QueryCmd::Expand {
            id,
            index,
            depth,
            kind,
            direction,
        } => (
            index,
            QueryRequest::Expand {
                id: SymbolId(id),
                depth,
                kinds: parse_kinds(&kind)?,
                direction: Direction::from_str(&direction)?,
            },
        ),
        QueryCmd::Findings {
            index,
            rule,
            path_prefix,
            symbol_id,
        } => (
            index,
            QueryRequest::Findings {
                filter: FindingFilter {
                    rule_id: rule,
                    path_prefix,
                    symbol_id: symbol_id.map(SymbolId),
                },
            },
        ),
        QueryCmd::SymbolsInFile { path, index } => (index, QueryRequest::SymbolsInFile { path }),
        QueryCmd::EdgesByFile {
            path,
            index,
            kind,
            direction,
        } => (
            index,
            QueryRequest::EdgesByFile {
                path,
                kinds: parse_kinds(&kind)?,
                direction: Direction::from_str(&direction)?,
            },
        ),
        QueryCmd::UnresolvedCallers { index, name, kind } => (
            index,
            QueryRequest::UnresolvedCallers {
                names: name,
                kinds: parse_kinds(&kind)?,
            },
        ),
        QueryCmd::ImportersOf { path, index } => (index, QueryRequest::ImportersOfFile { path }),
        QueryCmd::Files { index, prefix } => (index, QueryRequest::FilesAtPrefix { prefix }),
        QueryCmd::Metadata { index } => (index, QueryRequest::Metadata),
        QueryCmd::Find { index, qname } => (index, QueryRequest::FindByQname { qname }),
        QueryCmd::BlastRadius { index, qname } => (index, QueryRequest::BlastRadius { qname }),
        QueryCmd::TestSeams { index, qname } => (index, QueryRequest::TestSeams { qname }),
    })
}
